name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: /opt/android-sdk

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2

    - name: Create local.properties
      run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build
